### ISSUE TITLE
Support for ESP8266

### ISSUE THREAD

**Issue by StevenCellist** [radiolib-org/radiolib-persistence#1]
Originally requested by @Lasermax3000 on the RadioLib repository: actual support for the ESP8266.

There seems to be no genuine implementation of EEPROM, apart from the sketchy implementation that is also available for ESP32. However, since the Nonces buffer is only 16 bytes, it shouldn't be too bad (paging @ropg: can you tell, please, if writing these 16 bytes doesn't have weird write/erase side effects?). Plus only writing upon joining makes it not bad at all.

The following link demonstrates the use of RTC RAM: https://arduino.stackexchange.com/questions/91580/esp8266-rtc-memory-for-bootcount
Luckily, it appears there's just enough RAM to fit a session and have a bit spare for user application.

**Comment by ropg** [comment]
I started on ESP32s, so never worked much with 8266s. I'm not happy with how the ESP NVM key/value storage works in general, but writing a 16-byte blob is fine, esp. since the nonces don't change as often.

**Comment by StevenCellist** [comment]
I only ever used 8266 once.. and ESP32 on all other occasions :) but would you even say that you prefer 16-byte EEPROM blob over Preferences.h, or is Preferences still preferred then?

**Comment by StevenCellist** [comment]
@Lasermax3000 I had a few dull hours this morning, so I built a sketch that _might_ work. It compiles, but I do not have any ESP8266 around me right now to test it on. 
RadioLib 6.5.0 will come out this evening likely which is the version that is required for this sketch to even compile (or you can download the current [RadioLib source](https://github.com/jgromes/RadioLib) if you want to check it out before 6.5.0 is released).
Please report your experience, and if possible it would be nice if you can enable the `RADIOLIB_DEBUG_PROTOCOL` flag and share the output of your device :)

**Comment by StevenCellist** [comment]
@ropg sounds like EEPROM will work just fine for the foreseeable future, thanks :)
We can see later about saving sessions to EEPROM intelligently, but that's another story.
