### ISSUE TITLE
ESP8266 example failed

### ISSUE THREAD

**Issue by Lasermax3000** [radiolib-org/radiolib-persistence#3]
I´m sorry but i tested my device with your Example Code an there seems to be an issue. 
I get the following Output:

Recalling boot counts
Initalise the radio
Recalling LoRaWAN nonces & session
Restoring session buffer failed(-1115)     //The buffer integrity check did not match the supplied checksum value. 
Setup LoRaWAN session
Restore session failed(-1101)                   //Unable to restore existing LoRaWAN session because this node did not join any network yet. 
Join ('login') to the LoRaWAN Network
Join failed: -1101
Boots since unsuccessful join: 2552311525
Retrying join in 180 seconds
Storing bootcount variables in RTC RAM
Sleeping 

What i don´t understand, is that the **bootCountSinceUnsuccessfulJoin** variable is a very high number? 
Even after Powercycle it´s still stored and not reset to zero? 
Could it be a Problem, that the RTC Memory is in 4 Byte Blocks and the Pointer from the **uint8_t LWsession** array is casted to uint32_t and stored afterwards?
When i got more time i will try the device on another location, i´m not sure why the Join Procedure does not seem work too. 
Maybe you got any futher tips for me, what i could try to find out, where the dog is buried.

**Comment by StevenCellist** [comment]
Hi @Lasermax3000, thanks for testing! The problem is not with the uint8_t/uint32_t; the problem is with RTC RAM initializing to random values when it is reset. Apparently, I failed to polish the last few bits.

What device do you use? I only have a generic ESP8266 and hijack an SX1262 from another device, but that setup _sucks_, I have to pull and plug wires because the GPIO have weird behaviour when rebooting...

**Comment by Lasermax3000** [comment]
Ok thanks you´re right that makes sence, the RTC Memory needs to be initialised once, i will add that and try if it fixes this huge value problem. 

I use a NodeMCU ESP8266 with a HopeRF RFM95W Module. 

Are you sure this casting to uint32_t does the job? 
e.g. this Line **ESP.rtcUserMemoryWrite(address, (uint32_t *) LWsession, RADIOLIB_LORAWAN_SESSION_BUF_SIZE))**

Correct me if i´m wrong, but from my understanding this will write 396 entries with a sizeof(uint_32_t) = 4 Bytes which is is far bigger than the maximum size of the RTC Memory ( 4*396 > 512 (maximum available Bytes)) according to 
the description on this Site [https://hackaday.io/project/24993/instructions].

Every entry in the Memory i think looks like this [Byte3, Byte2, Byte1,  LWsession_dataByte].
Or do i understand this wrong, since i´m not a very experienced programmer? 
So it might be better to copy the content of LWsession to a uint32_t array and store this. 
I will try it out on occasion.

**Comment by StevenCellist** [comment]
Don't ask me why, but that pointer stuff works. I have an idea to fix the weird boot count; fixing it has been scheduled, got to fix some smoll bugs in RadioLib first. And unbrick a device. Let me know if you get around to something working before I do!

**Comment by StevenCellist** [comment]
Should be good now! Slightly improved my setup and it ran fine for a handful of uplinks, reporting bootcount 1,2,3...
