### ISSUE TITLE
LR1110: setRfSwitchTable is problematic

### ISSUE THREAD

**Issue by tve** [radiolib-org/radiolib-persistence#7]
Issue1: in most of the LR11x0 examples setRfSwitchTable is called before `begin()` but it has to be called after. Example: https://github.com/jgromes/RadioLib/blob/master/examples/LR11x0/LR11x0_Transmit_Blocking/LR11x0_Transmit_Blocking.ino#L66

Issue2: The table used for setRfSwitchTable for the LR1110 must have all possible state rows and all 5 columns for all 5 possible pins according to https://github.com/jgromes/RadioLib/blob/master/src/modules/LR11x0/LR11x0.cpp#L1456-L1460

I had something like:

```
static const uint32_t rfswitch_dio_pins[] = {
  // DIO5:LNAEN, DIO6:VRFSW, DIO8:RFSW
  RADIOLIB_LR11X0_DIO5, RADIOLIB_LR11X0_DIO6, RADIOLIB_LR11X0_DIO8,
  RADIOLIB_NC, RADIOLIB_NC
};

static const Module::RfSwitchMode_t rfswitch_table[] = {
  // mode                  DIO5  DIO6  DIO8
  { LR11x0::MODE_STBY,   { LOW,  LOW,  LOW  } },
  { LR11x0::MODE_RX,     { LOW,  HIGH, LOW  } },
  { LR11x0::MODE_TX,     { LOW,  HIGH, HIGH } },
  { LR11x0::MODE_GNSS,   { HIGH, LOW,  LOW  } },
  END_OF_MODE_TABLE,
};
```
and this does not work at all.

(On issue 2 I'm not arguing how it should work except that if it's completely different then the docs for the method should mention it.)

**Comment by StevenCellist** [comment]
This looks like it should be an issue on the main repository?

**Comment by tve** [comment]
Indeed! Thanks for catching that and sorry for the noise. Too many tabs open...
